[tool.poetry]
name = "pac"
version = "0.1.0"
description = ""
authors = ["dpgffhemig <dpgf@fhemig.mg.gov.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mkdocs = "^1.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
